name: AeqB
version: 0.1.0.0
github: githubuser/AeqB
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2022 Author name here

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/githubuser/AeqB#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - free >= 5.1.7
  - mtl >= 2.2.2
  - megaparsec >= 9.2.1
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  AeqB-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - AeqB
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  AeqB-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - AeqB
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
